name: "github"

on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  Check_Checkboxes:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.issues.listLabelsOnIssue({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
            });
            print(result)
